name: Send Email When Issue Created

on:
  issues:
    types: [opened]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🆕 New GitHub Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: GitHub Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            A new issue has been created on repository **${{ github.repository }}**.

            **Title:** ${{ github.event.issue.title }}
            **Author:** ${{ github.event.issue.user.login }}
            **URL:** ${{ github.event.issue.html_url }}

            ---
            **Description:**
            ${{ github.event.issue.body }}
